#:include kv/startscreen.kv
#:include kv/homescreen.kv
#:include kv/secondscreen.kv

GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager
        StartScreen:
            name: "start_screen"
            id: start_screen
        HomeScreen:
            name: "home_screen"
            id: home_screen
        SecondScreen:
            name: "second_screen"
            id: second_screen